services:
  postgres:
    image: 'postgres:18-alpine'
    environment:
      - 'POSTGRES_DB=glowlytic'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d glowlytic" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/luan-tran/glowlytic-be:main
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/glowlytic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      -
volumes:
  postgres_data: